let a = 0;
let b = 1;
try {
    console.log(a + c)
} catch (error) {
    console.log("erro:" + error)
}